[package]
name = "streamx"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "Stream extensions."
repository = "https://github.com/vilicvane/streamx"

[dependencies]
async-broadcast = "0.7"
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }

[lints.clippy]
collapsible_else_if = "allow"
disallowed_macros = "warn"
too_many_arguments = "allow"
type_complexity = "allow"
module_inception = "allow"

[dev-dependencies]
lits = "0.3.1"
tokio = { version = "1", features = ["full"] }
